### ISSUE TITLE
Failing on external reference (purple) fields ?

### ISSUE THREAD

**Issue by adywren** [OhmSweetOhm/CobieQcReporter#18]
Despite populating ExtSystem, ExtObject & ExtIdentifier the QC reporter is failing Floor, Space, Zone, Type datasheets. 

e.g. COBie.Space
CreatedBy: 0, CreatedOn: 0, ExtSystem: 121, ExtObject: 121, ExtIdentifier: 121, Category: 0, Name: 0, FloorName: 0, Description: 0, RoomTag: 0, UsableHeight: 0, GrossArea: 0, NetArea: 0

![image](https://user-images.githubusercontent.com/35028800/178010423-1d1d1116-08d7-42ee-aa7c-070e59018bd0.png)

Any ideas why?.. no failures throughout the rest of the COBie file.

Regards,
Ady

**Comment by salpbes** [comment]
Did you try to change column headings from "Ext" to "External".
For example:
"**Ext**System" to "**External**System"

**Comment by adywren** [comment]
https://github.com/OhmSweetOhm/CobieQcReporter/issues/18#issuecomment-1192780242

Many thanks, our xls matched the BS1192-4 / COBie 2021 UK standard, replacing 'Ext' with 'External' as per NBIMs V3 4.2 solved the issue.
