### ISSUE TITLE
Issue with trimming

### ISSUE THREAD

**Issue by cornhegne** [OhmSweetOhm/CobieQcReporter#2]
Received 420 false-positive readings on components not being correctly placed in spaces due to lack of trimming the source COBie file. I had to go back and trim(clean(x)) 1,800 rows of data. Didn't take long but was a bit frustrating. 

Did we decide that all checks were to be tested against data trimmed by the checker or not?

**Comment by cornhegne** [comment]
Had another example of a bad space number reference in component. manually entered the correct space number. QCReporter failed. It appears when you make manual data entry, that cell must be trim(clean(x)) to get it to match up again.  Not good...

**Comment by OhmSweetOhm** [comment]
It looks like this isn't a leading/trailing space issue but a decimal value issue.  Somehow Space 103 is being exported as 103.0.  Not sure if this is a spreadsheet formatting issue or a code issue.  Investigating.  Sorry for the issue.

**Comment by OhmSweetOhm** [comment]
To clarify, that issue was happening with any of the space names that were integer numbers, not just 103.

**Comment by cornhegne** [comment]
Wowie….  so making sure that everything is formatted as text is pretty critical here.

**Comment by OhmSweetOhm** [comment]
I examined the Excel file and even when you format the column as text Excel is storing some of those cells as numeric types (floating point by default).  When the export code encounters a numeric type it converts it to a string.  I need to add some code to possibly do an integer formatting preference for whole numbers.
