### ISSUE TITLE
No Table of Contents

### ISSUE THREAD

**Issue by pfurbish** [OhmSweetOhm/CobieQcReporter#4]
The QC Reporter html output is missing a table of contents.   There are numerous <a> elements for #TOC.
I was expecting a table of contents similar to the one included the COBie Toolkit QC report. 

Great tool.  Thanks.
Paul

**Comment by OhmSweetOhm** [comment]
That summary table at the beginning of the QC report is the table of contents.  You should be able to click on the Worksheet and Row Error Count table cells to navigate to specific sections of the report.  Please let me know if this isn't working for you.  Also, I can't remember how the old reporter Table of Contents differed.  Do you happen to have a screenshot or an old report you could send me?

**Comment by pfurbish** [comment]
Below is an example of the TOC in the earlier tool.  It has links to the
summary and detailed error sections, which are handy but not absolutely
necessary.

Thanks.
Paul


Table of Contents
 1 QC Summary    1.1 COBie Summary Table    1.2 COBie.Contacts  (row count
check)    1.3 COBie.Facilities  (row count check)    1.4
COBie.Facilities.Facility
(checked 1 row)    1.5 COBie.Floors  (row count check)    1.6
COBie.Floors.Floor
(checked 9 rows)    1.7 COBie.Spaces  (row count check)    1.8
COBie.Spaces.Space
(checked 87 rows)    1.9 COBie.Types  (row count check)    1.10
COBie.Types.Type
(checked 122 rows)    1.11 COBie.Components  (row count check)    1.12
COBie.Components.Component
(checked 508 rows)    1.13 COBie.Documents.Document  (checked 11 rows)
   1.14 COBie.Attributes.Attribute
(checked 33 rows) 2 Detailed Error Report Grouped by Error/Warning
Type    2.1 COBie.Contacts
(1 invalid worksheet error(s), 0 warnings)    2.2 COBie.Facilities.Facility
(1 invalid row , 0 warnings)    2.3 COBie.Floors.Floor (9 invalid rows, 0
warnings)    2.4 COBie.Spaces.Space (87 invalid rows, 0 warnings)
2.5 COBie.Types.Type
(122 invalid rows, 0 warnings)    2.6 COBie.Components.Component (508
invalid rows, 0 warnings)    2.7 COBie.Documents.Document (11 invalid rows,
0 warnings)    2.8 COBie.Attributes.Attribute (33 invalid rows, 0 warnings) 3
Detailed Error Report Grouped by Row    3.1 COBie.Contacts (1 invalid
worksheet error(s), 0 warnings)    3.2 COBie.Facilities.Facility (1 invalid
row , 0 warnings)    3.3 COBie.Floors.Floor (9 invalid rows, 0
warnings)    3.4 COBie.Spaces.Space
(87 invalid rows, 0 warnings)    3.5 COBie.Types.Type (122 invalid rows, 0
warnings)    3.6 COBie.Components.Component (508 invalid rows, 0
warnings)    3.7 COBie.Documents.Document
(11 invalid rows, 0 warnings)    3.8 COBie.Attributes.Attribute (33 invalid
rows, 0 warnings)

**Comment by OhmSweetOhm** [comment]
The current report still has the same sort of functionality, but now you navigate by clicking cells of the Summary table.  For example, if you click on the "Contact" cell in the attached Summary table, it navigates to the section that describes the Contact checks that were performed (see second attachment).  Similarly, if you click on a non-zero "Row Error Count" number, it will navigate to a section of the report that provides details regarding the errors for that corresponding sheet.  The "Table of Contents" links navigate back to the Summary table.  

![image](https://user-images.githubusercontent.com/1241936/31751673-4f3ea8da-b44c-11e7-9aa7-fc85fd937e92.png)

![image](https://user-images.githubusercontent.com/1241936/31751723-9b0089aa-b44c-11e7-9e97-88da3b75efb1.png)

**Comment by pfurbish** [comment]
Thanks for the explanation.

Paul
