### ISSUE TITLE
N/A slipping into Component.Space undetected

### ISSUE THREAD

**Issue by for59j54** [OhmSweetOhm/CobieQcReporter#5]
Issue where n/a can slip into component.space. can contain entries that are not found on the space.name sheet but passes anyway.
Attached is the sheet that passes and the passing report
[cobie_test.xlsx](https://github.com/OhmSweetOhm/CobieQcReporter/files/1315621/cobie_test.xlsx)
[testdesignqc.zip](https://github.com/OhmSweetOhm/CobieQcReporter/files/1315624/testdesignqc.zip)

**Comment by OhmSweetOhm** [comment]
Thanks for reporting the issue.  I missed the notification of this github issue in my email but Bill made me aware of the issue.  There was a bug in the logic for checking comma-delimited spaces for windows - an inconsistency in how a couple of XSL processors handled one of the checking functions.  

I found the bug and fixed it.  Bill and I are testing now.  Thank you so much for reporting this.  This bug has been creeping for a long time.

**Comment by for59j54** [comment]
No Problem
I like this tool & promote it so if I find further issues I will let you know.


Regards

John Ford
Business Information Manager | Technical BIM Lead

84 Salop Street | Wolverhampton | WV1 4HY | United Kingdom
T:  +44 (0) 1902 912 721
M: +44 (0) 7891 567 627
E: John.Ford@carillionplc.com<mailto:John.Ford@carillionplc.com> | www.carillionplc.com<http://www.carillionplc.com/> |

**Comment by OhmSweetOhm** [comment]
I just uploaded a new release that SHOULD fix the issue.  Check the releases page for the latest.

**Comment by for59j54** [comment]
This seems to be sorted. Thanks & good job


Regards

John Ford
Business Information Manager | Technical BIM Lead

84 Salop Street | Wolverhampton | WV1 4HY | United Kingdom
T:  +44 (0) 1902 912 721
M: +44 (0) 7891 567 627
E: John.Ford@carillionplc.com<mailto:John.Ford@carillionplc.com> | www.carillionplc.com<http://www.carillionplc.com/> |
